[package]
name = "wikimedia_jp_queue_bot"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "daily_page_create"
path = "src/bin/daily_page_create.rs"

[[bin]]
name = "queue_consume"
path = "src/bin/queue_consume.rs"

[dependencies]
anyhow = "1.0.75"
chrono = { version = "0.4.31", default-features = false, features = [
    "std",
    "clock",
] }
config = { version = "0.13.3", default-features = false, features = ["toml"] }
futures-util = "0.3.28"
if_chain = "1.0.2"
indexmap = "2.0.2"
indexmap19 = { version = "1.9.3", package = "indexmap" } # for mwbot
indoc = "2.0.4"
kuchiki = "0.8.1"
markup5ever = "0.11.0"
mwapi_responses = "0.3.4"
mwbot = "0.5.3"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = [
    "tls-rustls",
    "mysql",
    "json",
    "uuid",
    "macros",
    "runtime-tokio",
] }
tap = "1.0.1"
tokio = { version = "1.33.0", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "signal",
] }
tokio-retry = "0.3.0"
tracing = "0.1.39"
tracing-subscriber = "0.3.17"
ulid = { version = "1.1.0", features = ["uuid"] }
uuid = "1.5.0"

[dev-dependencies]
indoc = "2.0.4"
pretty_assertions = "1.4.0"
