services:
  database:
    image: mariadb:10.11.9
    environment:
      - MARIADB_USER=queuebot
      - MARIADB_PASSWORD=password
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=queuebot
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  sqldef:
    image: ghcr.io/mirror-kt/mysqldef:0.17.20
    command: "-h database -uqueuebot -ppassword queuebot --file ./migration/def.sql"
    working_dir: /work
    volumes:
      - "./migration:/work/migration"
    depends_on:
      database:
        condition: service_healthy
