on: [push, pull_request]

jobs:
  cargo:
    name: cargo clippy & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DATABASE_URL: 'mysql://queuebot:password@127.0.0.1/queuebot'
      - run: cargo test
        env:
          DATABASE_URL: 'mysql://queuebot:password@127.0.0.1/queuebot'
